/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Mon Sep 10 17:17:33 2018. */

#ifndef PB_IOT_PAIRING_SENSOR_DATA_PB_H_INCLUDED
#define PB_IOT_PAIRING_SENSOR_DATA_PB_H_INCLUDED
#include <pb.h>

#include "google/protobuf/timestamp.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _IoT_pairing_GenericDataArray_ArrayType {
    IoT_pairing_GenericDataArray_ArrayType_ORIENTATION = 0,
    IoT_pairing_GenericDataArray_ArrayType_LINEAR_ACCEL = 1,
    IoT_pairing_GenericDataArray_ArrayType_GRAVITY = 2,
    IoT_pairing_GenericDataArray_ArrayType_ACCEL = 3,
    IoT_pairing_GenericDataArray_ArrayType_GYRO = 4,
    IoT_pairing_GenericDataArray_ArrayType_MAG = 5
} IoT_pairing_GenericDataArray_ArrayType;
#define _IoT_pairing_GenericDataArray_ArrayType_MIN IoT_pairing_GenericDataArray_ArrayType_ORIENTATION
#define _IoT_pairing_GenericDataArray_ArrayType_MAX IoT_pairing_GenericDataArray_ArrayType_MAG
#define _IoT_pairing_GenericDataArray_ArrayType_ARRAYSIZE ((IoT_pairing_GenericDataArray_ArrayType)(IoT_pairing_GenericDataArray_ArrayType_MAG+1))

/* Struct definitions */
typedef struct _IoT_pairing_GenericDataBlock {
    pb_callback_t values;
/* @@protoc_insertion_point(struct:IoT_pairing_GenericDataBlock) */
} IoT_pairing_GenericDataBlock;

typedef struct _IoT_pairing_CalibrationStatus {
    uint32_t overall;
    uint32_t accel;
    uint32_t gyro;
    uint32_t mag;
/* @@protoc_insertion_point(struct:IoT_pairing_CalibrationStatus) */
} IoT_pairing_CalibrationStatus;

typedef struct _IoT_pairing_GenericDataArray {
    pb_size_t data_x_count;
    float data_x[50];
    pb_size_t data_y_count;
    float data_y[50];
    pb_size_t data_z_count;
    float data_z[50];
    IoT_pairing_GenericDataArray_ArrayType magnitude;
    google_protobuf_Timestamp t_latest;
    float F_samp;
/* @@protoc_insertion_point(struct:IoT_pairing_GenericDataArray) */
} IoT_pairing_GenericDataArray;

typedef struct _IoT_pairing_QuatArray {
    pb_size_t x_count;
    float x[50];
    pb_size_t y_count;
    float y[50];
    pb_size_t z_count;
    float z[50];
    pb_size_t w_count;
    float w[50];
/* @@protoc_insertion_point(struct:IoT_pairing_QuatArray) */
} IoT_pairing_QuatArray;

typedef struct _IoT_pairing_XYZArray {
    pb_size_t x_count;
    float x[50];
    pb_size_t y_count;
    float y[50];
    pb_size_t z_count;
    float z[50];
/* @@protoc_insertion_point(struct:IoT_pairing_XYZArray) */
} IoT_pairing_XYZArray;

typedef struct _IoT_pairing_DataBlock {
    IoT_pairing_QuatArray orientation;
    IoT_pairing_XYZArray linearAccel;
    IoT_pairing_XYZArray gravity;
    IoT_pairing_XYZArray accel;
    IoT_pairing_XYZArray gyro;
    IoT_pairing_XYZArray mag;
    google_protobuf_Timestamp t_latest;
    float F_samp;
    uint32_t id;
    IoT_pairing_CalibrationStatus calibStatus;
/* @@protoc_insertion_point(struct:IoT_pairing_DataBlock) */
} IoT_pairing_DataBlock;

/* Default values for struct fields */

/* Initializer values for message structs */
#define IoT_pairing_GenericDataArray_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, _IoT_pairing_GenericDataArray_ArrayType_MIN, google_protobuf_Timestamp_init_default, 0}
#define IoT_pairing_GenericDataBlock_init_default {{{NULL}, NULL}}
#define IoT_pairing_XYZArray_init_default        {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define IoT_pairing_QuatArray_init_default       {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define IoT_pairing_CalibrationStatus_init_default {0, 0, 0, 0}
#define IoT_pairing_DataBlock_init_default       {IoT_pairing_QuatArray_init_default, IoT_pairing_XYZArray_init_default, IoT_pairing_XYZArray_init_default, IoT_pairing_XYZArray_init_default, IoT_pairing_XYZArray_init_default, IoT_pairing_XYZArray_init_default, google_protobuf_Timestamp_init_default, 0, 0, IoT_pairing_CalibrationStatus_init_default}
#define IoT_pairing_GenericDataArray_init_zero   {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, _IoT_pairing_GenericDataArray_ArrayType_MIN, google_protobuf_Timestamp_init_zero, 0}
#define IoT_pairing_GenericDataBlock_init_zero   {{{NULL}, NULL}}
#define IoT_pairing_XYZArray_init_zero           {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define IoT_pairing_QuatArray_init_zero          {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define IoT_pairing_CalibrationStatus_init_zero  {0, 0, 0, 0}
#define IoT_pairing_DataBlock_init_zero          {IoT_pairing_QuatArray_init_zero, IoT_pairing_XYZArray_init_zero, IoT_pairing_XYZArray_init_zero, IoT_pairing_XYZArray_init_zero, IoT_pairing_XYZArray_init_zero, IoT_pairing_XYZArray_init_zero, google_protobuf_Timestamp_init_zero, 0, 0, IoT_pairing_CalibrationStatus_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define IoT_pairing_GenericDataBlock_values_tag  1
#define IoT_pairing_CalibrationStatus_overall_tag 1
#define IoT_pairing_CalibrationStatus_accel_tag  2
#define IoT_pairing_CalibrationStatus_gyro_tag   3
#define IoT_pairing_CalibrationStatus_mag_tag    4
#define IoT_pairing_GenericDataArray_data_x_tag  1
#define IoT_pairing_GenericDataArray_data_y_tag  2
#define IoT_pairing_GenericDataArray_data_z_tag  3
#define IoT_pairing_GenericDataArray_magnitude_tag 4
#define IoT_pairing_GenericDataArray_t_latest_tag 5
#define IoT_pairing_GenericDataArray_F_samp_tag  6
#define IoT_pairing_QuatArray_w_tag              4
#define IoT_pairing_QuatArray_x_tag              1
#define IoT_pairing_QuatArray_y_tag              2
#define IoT_pairing_QuatArray_z_tag              3
#define IoT_pairing_XYZArray_x_tag               1
#define IoT_pairing_XYZArray_y_tag               2
#define IoT_pairing_XYZArray_z_tag               3
#define IoT_pairing_DataBlock_orientation_tag    1
#define IoT_pairing_DataBlock_linearAccel_tag    2
#define IoT_pairing_DataBlock_gravity_tag        3
#define IoT_pairing_DataBlock_accel_tag          4
#define IoT_pairing_DataBlock_gyro_tag           5
#define IoT_pairing_DataBlock_mag_tag            6
#define IoT_pairing_DataBlock_t_latest_tag       7
#define IoT_pairing_DataBlock_F_samp_tag         8
#define IoT_pairing_DataBlock_id_tag             9
#define IoT_pairing_DataBlock_calibStatus_tag    10

/* Struct field encoding specification for nanopb */
extern const pb_field_t IoT_pairing_GenericDataArray_fields[7];
extern const pb_field_t IoT_pairing_GenericDataBlock_fields[2];
extern const pb_field_t IoT_pairing_XYZArray_fields[4];
extern const pb_field_t IoT_pairing_QuatArray_fields[5];
extern const pb_field_t IoT_pairing_CalibrationStatus_fields[5];
extern const pb_field_t IoT_pairing_DataBlock_fields[11];

/* Maximum encoded size of messages (where known) */
#define IoT_pairing_GenericDataArray_size        781
/* IoT_pairing_GenericDataBlock_size depends on runtime parameters */
#define IoT_pairing_XYZArray_size                750
#define IoT_pairing_QuatArray_size               1000
#define IoT_pairing_CalibrationStatus_size       24
#define IoT_pairing_DataBlock_size               4829

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SENSOR_DATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
