/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Sep 10 20:29:46 2018. */

#include "sensor_data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t IoT_pairing_GenericDataArray_fields[7] = {
    PB_FIELD(  1, FLOAT   , REPEATED, STATIC  , FIRST, IoT_pairing_GenericDataArray, data_x, data_x, 0),
    PB_FIELD(  2, FLOAT   , REPEATED, STATIC  , OTHER, IoT_pairing_GenericDataArray, data_y, data_x, 0),
    PB_FIELD(  3, FLOAT   , REPEATED, STATIC  , OTHER, IoT_pairing_GenericDataArray, data_z, data_y, 0),
    PB_FIELD(  4, UENUM   , SINGULAR, STATIC  , OTHER, IoT_pairing_GenericDataArray, magnitude, data_z, 0),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, IoT_pairing_GenericDataArray, t_latest, magnitude, &google_protobuf_Timestamp_fields),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, IoT_pairing_GenericDataArray, F_samp, t_latest, 0),
    PB_LAST_FIELD
};

const pb_field_t IoT_pairing_GenericDataBlock_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, IoT_pairing_GenericDataBlock, values, values, &IoT_pairing_GenericDataArray_fields),
    PB_LAST_FIELD
};

const pb_field_t IoT_pairing_XYZArray_fields[4] = {
    PB_FIELD(  1, FLOAT   , REPEATED, STATIC  , FIRST, IoT_pairing_XYZArray, x, x, 0),
    PB_FIELD(  2, FLOAT   , REPEATED, STATIC  , OTHER, IoT_pairing_XYZArray, y, x, 0),
    PB_FIELD(  3, FLOAT   , REPEATED, STATIC  , OTHER, IoT_pairing_XYZArray, z, y, 0),
    PB_LAST_FIELD
};

const pb_field_t IoT_pairing_QuatArray_fields[5] = {
    PB_FIELD(  1, FLOAT   , REPEATED, STATIC  , FIRST, IoT_pairing_QuatArray, x, x, 0),
    PB_FIELD(  2, FLOAT   , REPEATED, STATIC  , OTHER, IoT_pairing_QuatArray, y, x, 0),
    PB_FIELD(  3, FLOAT   , REPEATED, STATIC  , OTHER, IoT_pairing_QuatArray, z, y, 0),
    PB_FIELD(  4, FLOAT   , REPEATED, STATIC  , OTHER, IoT_pairing_QuatArray, w, z, 0),
    PB_LAST_FIELD
};

const pb_field_t IoT_pairing_CalibrationStatus_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, IoT_pairing_CalibrationStatus, overall, overall, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, IoT_pairing_CalibrationStatus, accel, overall, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, IoT_pairing_CalibrationStatus, gyro, accel, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, IoT_pairing_CalibrationStatus, mag, gyro, 0),
    PB_LAST_FIELD
};

const pb_field_t IoT_pairing_DataBlock_fields[11] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, IoT_pairing_DataBlock, orientation, orientation, &IoT_pairing_QuatArray_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, IoT_pairing_DataBlock, linearAccel, orientation, &IoT_pairing_XYZArray_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, IoT_pairing_DataBlock, gravity, linearAccel, &IoT_pairing_XYZArray_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, IoT_pairing_DataBlock, accel, gravity, &IoT_pairing_XYZArray_fields),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, IoT_pairing_DataBlock, gyro, accel, &IoT_pairing_XYZArray_fields),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, IoT_pairing_DataBlock, mag, gyro, &IoT_pairing_XYZArray_fields),
    PB_FIELD(  7, MESSAGE , SINGULAR, STATIC  , OTHER, IoT_pairing_DataBlock, t_latest, mag, &google_protobuf_Timestamp_fields),
    PB_FIELD(  8, FLOAT   , SINGULAR, STATIC  , OTHER, IoT_pairing_DataBlock, F_samp, t_latest, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, IoT_pairing_DataBlock, id, F_samp, 0),
    PB_FIELD( 10, MESSAGE , SINGULAR, STATIC  , OTHER, IoT_pairing_DataBlock, calibStatus, id, &IoT_pairing_CalibrationStatus_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(IoT_pairing_GenericDataArray, t_latest) < 65536 && pb_membersize(IoT_pairing_DataBlock, orientation) < 65536 && pb_membersize(IoT_pairing_DataBlock, linearAccel) < 65536 && pb_membersize(IoT_pairing_DataBlock, gravity) < 65536 && pb_membersize(IoT_pairing_DataBlock, accel) < 65536 && pb_membersize(IoT_pairing_DataBlock, gyro) < 65536 && pb_membersize(IoT_pairing_DataBlock, mag) < 65536 && pb_membersize(IoT_pairing_DataBlock, t_latest) < 65536 && pb_membersize(IoT_pairing_DataBlock, calibStatus) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_IoT_pairing_GenericDataArray_IoT_pairing_GenericDataBlock_IoT_pairing_XYZArray_IoT_pairing_QuatArray_IoT_pairing_CalibrationStatus_IoT_pairing_DataBlock)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(IoT_pairing_GenericDataArray, t_latest) < 256 && pb_membersize(IoT_pairing_DataBlock, orientation) < 256 && pb_membersize(IoT_pairing_DataBlock, linearAccel) < 256 && pb_membersize(IoT_pairing_DataBlock, gravity) < 256 && pb_membersize(IoT_pairing_DataBlock, accel) < 256 && pb_membersize(IoT_pairing_DataBlock, gyro) < 256 && pb_membersize(IoT_pairing_DataBlock, mag) < 256 && pb_membersize(IoT_pairing_DataBlock, t_latest) < 256 && pb_membersize(IoT_pairing_DataBlock, calibStatus) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_IoT_pairing_GenericDataArray_IoT_pairing_GenericDataBlock_IoT_pairing_XYZArray_IoT_pairing_QuatArray_IoT_pairing_CalibrationStatus_IoT_pairing_DataBlock)
#endif


/* @@protoc_insertion_point(eof) */
